In [1]:
import torch

In [2]:
A_logit = torch.tensor([7, 3, 2], dtype=torch.float32)
B_logit = torch.tensor([9, -2, 8], dtype=torch.float32)

A_prob = torch.nn.functional.softmax(A_logit, dim=0)
B_prob = torch.nn.functional.softmax(B_logit, dim=0)

In [3]:
M_logit = torch.tensor(0.77, dtype=torch.float32)
M_prob = torch.sigmoid(M_logit)
M_prob

tensor(0.6835)

In [4]:
C_prob = M_prob * A_prob + (1 - M_prob) * B_prob
C_prob

tensor([0.8982, 0.0122, 0.0896])

In [5]:
A_logprob = A_logit - torch.logsumexp(A_logit, dim=0)
B_logprob = B_logit - torch.logsumexp(B_logit, dim=0)

In [6]:
# using logprobs for A and B and logit for M
C_logprob = torch.log( M_prob * torch.exp(A_logprob) + (1 - M_prob) * torch.exp(B_logprob) )
torch.exp(C_logprob)

tensor([0.8982, 0.0122, 0.0896])

In [11]:
max_logprob = torch.maximum(A_logprob, B_logprob)
logsumexp = max_logprob + torch.log(
    M_prob * torch.exp(A_logprob - max_logprob) + (1 - M_prob) * torch.exp(B_logprob - max_logprob)
)
torch.exp(logsumexp)

tensor([0.8982, 0.0122, 0.0896])

In [10]:
def f(x, y):
    return torch.maximum(x, y) + torch.log(torch.exp(-torch.abs(x - y)))

torch.exp(f(A_logprob, B_logprob))

tensor([7.3105e-01, 1.2210e-05, 6.5733e-03])